# Generated by Django 6.0.1 on 2026-01-08 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos_global', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('intervalo_verificacao', models.IntegerField(default=60)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos_global.ativoslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrecoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos_global.ativoslist')),
            ],
        ),
    ]
