# Generated by Django 6.0.1 on 2026-01-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosuser',
            name='em_carteira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ativosuser',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
