# Generated by Django 6.0.1 on 2026-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosuser',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
