# Generated by Django 5.0 on 2023-12-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_user', '0002_codigoativo_remove_ativosuser_favorito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativosuser',
            name='codigo_ativo',
        ),
        migrations.AddField(
            model_name='ativosuser',
            name='codigo_ativo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cod_ativos', to='ativos_user.codigoativo'),
            preserve_default=False,
        ),
    ]
