# Generated by Django 5.0 on 2023-12-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_user', '0004_remove_ativosuser_em_carteira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoativo',
            name='variacao_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
