# Generated by Django 5.0 on 2023-12-07 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ativos_user", "0005_codigoativo_variacao_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="codigoativo",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ativosuser",
            name="codigo_ativo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cod_ativos",
                to="ativos_user.codigoativo",
            ),
        ),
    ]
