# Generated by Django 5.0 on 2023-12-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ativos_user", "0006_codigoativo_user_id_alter_ativosuser_codigo_ativo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativosuser",
            name="nome_empresa",
        ),
        migrations.AddField(
            model_name="codigoativo",
            name="nome_empresa",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
