# Generated by Django 5.0 on 2023-12-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ativos_user", "0007_remove_ativosuser_nome_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ativosuser",
            name="codigo_ativo",
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name="ativosuser",
            name="em_carteira",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ativosuser",
            name="favorito",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ativosuser",
            name="nome_empresa",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ativosuser",
            name="variacao_percent",
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CodigoAtivo",
        ),
    ]
