# Generated by Django 5.0 on 2023-12-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_user', '0009_alter_ativosuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativosuser',
            old_name='codigo_ativo',
            new_name='cod_ativo',
        ),
    ]
