# Generated by Django 5.0 on 2023-12-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_user', '0010_rename_codigo_ativo_ativosuser_cod_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosuser',
            name='id_ativo_list',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
