# Generated by Django 6.0.1 on 2026-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivosList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ativo', models.CharField(max_length=6)),
                ('nome_empresa', models.CharField(max_length=100)),
            ],
        ),
    ]
