# Generated by Django 5.0 on 2023-12-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_global', '0002_alter_ativoslist_cod_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ativoslist',
            old_name='empresa_nome',
            new_name='nome_empresa',
        ),
    ]
