# Generated by Django 5.0 on 2023-12-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos_global', '0003_rename_empresa_nome_ativoslist_nome_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativoslist',
            name='cod_ativo',
            field=models.CharField(max_length=6),
        ),
    ]
