# Generated by Django 5.0 on 2023-12-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('nome_empresa', models.CharField(max_length=100)),
                ('codigo_ativo', models.CharField(max_length=5)),
                ('favorito', models.BooleanField()),
                ('em_carteira', models.BooleanField()),
            ],
        ),
    ]
